#!/usr/bin/env bash
#=========================================================================
# 02-synopsys-dc-synth
#=========================================================================

# Stop on error and echo all commands

set -e
trap 'echo "CMD: $BASH_COMMAND"' DEBUG

# Determine RUNDIR

RUNDIR="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))"
cd $RUNDIR

# Run using run.tcl script

dc_shell-xg-t -f run.tcl | tee run.log

